function(setup)
{
    ['%(pfx)stao-portal-be-env' % setup]: {
  # AI_API_URL: "http://tao-ce-tao-ai-api:3000",
  AUTH_SERVER_API_URL: "http://tao-ce-em-auth-server:8080",
  # CLASSIFICATION_API_URL: "http://tao-ce-tao-classification-be:3000",
  # CONTENT_API_URL: "http://tao-ce-tao-content-be:3000",
  DYNAMIC_API_URL: "http://tao-ce-tao-dynamic-query-api:3000",
  ELASTICSEARCH_URL: setup.dependencies.es.address.url,
  FIRESTORE_EMULATOR_HOST: setup.dependencies.firestore.address.endpoint,
  FIRESTORE_PROJECT_ID: self.GOOGLE_CLOUD_PROJECT,
  FIRESTORE_DATABASE_ID: "default",
  GCP_PROJECT_ID: self.GOOGLE_CLOUD_PROJECT,
  GOOGLE_CLOUD_PROJECT: setup.env.GOOGLE_CLOUD_PROJECT,
  # GCP_PUBLICATION_BUCKET_NAME: "nextgen-public-dev-geoffrey",
  GCP_PUBSUB_ACTIVITY_LOGS_TOPIC_NAME: "activity-logs-topic",
  GCP_PUBSUB_PAYMENT_STATUS_SUBSCRIPTION_NAME: "payment-api-payment-status-update-subscription",
  GCP_PUBSUB_PORTAL_SESSION_TEMPLATE_NOTIFICATION_TOPIC_NAME: "portal-session-template-notification",
  GCP_PUBSUB_SESSION_NOTIFICATION_SUBSCRIPTION_NAME: "session-notification-subscription",
  GCP_PUBSUB_SESSION_NOTIFICATION_TOPIC_NAME: "session-notification",
  GCP_PUBSUB_START_EXPORT_CSV_TOPIC_NAME: "start-export-csv-topic",
  GCP_PUBSUB_TASK_ORCHESTRATOR_TOPIC_NAME: "task-orchestrator-topic",
  GCP_PUBSUB_USERS_TOPIC_NAME: "users-ds",
  GCP_PUBSUB_USER_EVENTS_TOPIC_NAME: "portal-user-events",
  GCP_PUBSUB_DELIVERY_EXECUTIONS_SUBSCRIPTION_NAME: 'delivery-execution-portal',
  GCP_PUBSUB_GRADING_STATUSES_SUBSCRIPTION_NAME: 'grader-statuses-portal',
  GCP_PUBSUB_GRADING_SUBSCRIPTION_NAME: 'grader-manual-results-portal',
  GCP_PUBSUB_ACS_SUBSCRIPTION_NAME: 'acs-log-portal',
  GCP_PUBSUB_START_EXPORT_CSV_SUBSCRIPTION_NAME: 'start-export-csv-ds',
  GCP_PUBSUB_USERS_MERGE_SUBSCRIPTION_NAME: 'users-merge-subscription',
  GCP_PUBSUB_DELIVERY_CREATED_SUBSCRIPTION_NAME: 'portal-publications-subscription',
  GCP_PUBSUB_DELIVERY_PUBLICATION_FAILED_SUBSCRIPTION_NAME: 'delivery-publication-failed',
  GCP_PUBSUB_DELIVERY_LOCALE_ATTACHMENT_SUCCEEDED_SUBSCRIPTION_NAME: 'delivery-language-attachment-succeeded',
  GCP_PUBSUB_DELIVERY_LOCALE_ATTACHMENT_FAILED_SUBSCRIPTION_NAME: 'delivery-language-attachment-failed',
  GCP_PUBSUB_USER_EVENTS_SUBSCRIPTION_NAME: 'portal-user-events-subscription',
  GCP_PUBSUB_PORTAL_SESSION_TEMPLATE_NOTIFICATION_SUBSCRIPTION_NAME: 'portal-session-template-notification-subscription',
  HIERARCHY_API_URL: "http://tao-ce-hierarchy-be:3001",
  SIMPLE_REPORTS_API_URL: "https://%(publicDomain)s/sr-be/" % setup,
  INTEGRATION_API_URL: "http://tao-ce-tao-integration-api:3000",
  LOG_LEVEL: "trace",
  LTI_PORTAL_AUDIENCE: "https://%(publicDomain)s/portal-be" % setup,
  MANUAL_SCORING_API_URL: "http://tao-ce-tao-manual-scoring-be:80",
  NOTIFICATION_ENABLED_CHECK_CACHE_TTL_SEC: "60",
  PB_FIRESTORE_COLLECTION: "oat-dev",
  PUBSUB_EMULATOR_HOST: setup.dependencies.pubsub.address.url,
  SIDECAR_API_URL: "http://tao-ce-em-auth-server:8888",
  TASK_ORCHESTRATOR_API_URL: "http://tao-ce-tao-task-orchestrator-be:8080",
  TESTRUNNER_API_URL: "http://tao-ce-tao-deliver-be:80",
    },

        ['%(pfx)stao-portal-worker-env' % setup]: {
  AUTH_SERVER_API_URL: "http://tao-ce-em-auth-server:8080",
  DYNAMIC_API_URL: "http://tao-ce-tao-dynamic-query-api:3000",
  ELASTICSEARCH_URL: setup.dependencies.es.address.url,
  FIRESTORE_EMULATOR_HOST: setup.dependencies.firestore.address.endpoint,
  FIRESTORE_PROJECT_ID: self.GOOGLE_CLOUD_PROJECT,
  FIRESTORE_DATABASE_ID: "default",
  GCP_PROJECT_ID: self.GOOGLE_CLOUD_PROJECT,
  GOOGLE_CLOUD_PROJECT: setup.env.GOOGLE_CLOUD_PROJECT,
  GCP_PUBSUB_ACS_SUBSCRIPTION_NAME: "acs-log-portal",
  GCP_PUBSUB_ACTIVITY_LOGS_TOPIC_NAME: "activity-logs-topic",
  GCP_PUBSUB_DELIVERY_CREATED_SUBSCRIPTION_NAME: "portal-publications-subscription",
  GCP_PUBSUB_DELIVERY_EXECUTIONS_SUBSCRIPTION_NAME: "delivery-execution-portal",
  GCP_PUBSUB_DELIVERY_LOCALE_ATTACHMENT_FAILED_SUBSCRIPTION_NAME: "delivery-language-attachment-failed",
  GCP_PUBSUB_DELIVERY_LOCALE_ATTACHMENT_SUCCEEDED_SUBSCRIPTION_NAME: "delivery-language-attachment-succeeded",
  GCP_PUBSUB_DELIVERY_PUBLICATION_FAILED_SUBSCRIPTION_NAME: "delivery-publication-failed",
  GCP_PUBSUB_GRADING_STATUSES_SUBSCRIPTION_NAME: "grader-statuses-portal",
  GCP_PUBSUB_GRADING_SUBSCRIPTION_NAME: "grader-manual-results-portal",
  GCP_PUBSUB_PAYMENT_STATUS_SUBSCRIPTION_NAME: "payment-api-payment-status-update-subscription",
  GCP_PUBSUB_PORTAL_SESSION_TEMPLATE_NOTIFICATION_SUBSCRIPTION_NAME: "portal-session-template-notification-subscription",
  GCP_PUBSUB_PORTAL_SESSION_TEMPLATE_NOTIFICATION_TOPIC_NAME: "portal-session-template-notification",
  GCP_PUBSUB_SESSION_NOTIFICATION_SUBSCRIPTION_NAME: "session-notification-subscription",
  GCP_PUBSUB_SESSION_NOTIFICATION_TOPIC_NAME: "session-notification",
  GCP_PUBSUB_START_EXPORT_CSV_SUBSCRIPTION_NAME: "start-export-csv-ds",
  GCP_PUBSUB_START_EXPORT_CSV_TOPIC_NAME: "start-export-csv-topic",
  GCP_PUBSUB_TASK_ORCHESTRATOR_TOPIC_NAME: "task-orchestrator-topic",
  GCP_PUBSUB_USERS_MERGE_SUBSCRIPTION_NAME: "users-merge-subscription",
  GCP_PUBSUB_USERS_TOPIC_NAME: "users-ds",
  GCP_PUBSUB_USER_EVENTS_SUBSCRIPTION_NAME: "portal-user-events-subscription",
  GCP_PUBSUB_USER_EVENTS_TOPIC_NAME: "portal-user-events",
  GCP_PUBSUB_SESSION_GRADED_TOPIC_NAME: 'portal-session-graded-topic',
  HIERARCHY_API_URL: "http://tao-ce-hierarchy-be:3001",
  LOG_LEVEL: "trace",
  LTI_PORTAL_AUDIENCE: "https://%s/portal-be" % [setup.publicDomain],
  MANUAL_SCORING_API_URL: "http://tao-ce-tao-manual-scoring-be:80",
  NOTIFICATION_ENABLED_CHECK_CACHE_TTL_SEC: "60",
  PB_FIRESTORE_COLLECTION: "oat-dev",
  PUBSUB_EMULATOR_HOST: setup.dependencies.pubsub.address.url,
  SIDECAR_API_URL: "http://tao-ce-em-auth-server:8888",
  TASK_ORCHESTRATOR_API_URL: "http://tao-ce-tao-task-orchestrator-be:8080",
  TESTRUNNER_API_URL: "http://tao-ce-tao-deliver-be:80",
        },
    ['%(pfx)stao-portal-bootstrap-env' % setup]: {
  API_URL: "https://%(publicDomain)s/portal-be" % setup,
  AUTH_SERVER_URL: "https://%(publicDomain)s/auth-server" % setup,
  DELIVERY_PREVIEW_URL: "https://%(publicDomain)s/test-runner-sandbox" % setup,
  DELIVER_URL: "https://%(publicDomain)s/deliver" % setup,
  PATH_PREFIX: "/portal",
  PAYMENT_URL: "https://%(publicDomain)s/payments-be" % setup,
  RELEASE_VERSION: "oat-dev",
  SIMPLE_REPORTS_API_URL: "https://%(publicDomain)s/sr-be/" % setup,
  JSREPORT_URL: "https://%(publicDomain)s/jsreport/" % setup,
  REDIS_HOST: setup.dependencies.redis.address.url,
  STATIC_URL: "https://%(publicDomain)s/portal-static/" % setup,
//   STUDIO_URL: "https://%(publicDomain)s/studio" % setup,
  TASK_ORCHESTRATOR_API_URL: "http://tao-ce-tao-task-orchestrator-be:8080",
  TENANTS: "[{\"clientId\": \"portal-client-id_1\", \"label\": \"nextgen-stack\", \"subdomain\": \"community\", \"tenantId\": \"1\"}]",
//   WEBSOCKET_AI_PUBLIC_URL: "https://%(publicDomain)s/tao-ai-ws" % setup,
  WS_TASK_ORCHESTRATOR_URL: "https://%(publicDomain)s/task-orchestrator-socket" % setup,
    },
}