function(setup)

{
    ['%stao-env' % setup.pfx]: {
        CONSTRUCT_BASE_URL: "https://%s/backoffice/" % setup.publicDomain,
        PORTAL_BE_BASE_URL: "https://%s/portal-be" % setup.publicDomain,
        DELIVERTENANT_0_CUSTOMER_ID: "1",
        DELIVERTENANT_0_ID: "1",
        DELIVERTENANT_0_LABEL: "TAO Community Test Runner",
        DELIVERTENANT_0_LTI_1P3_AUDIENCE_URL: "https://%s" % setup.publicDomain,
        DELIVERTENANT_0_LTI_1P3_CREDENTIALS_0_CLIENT_ID: "backoffice-deliver-id",
        DELIVERTENANT_0_LTI_1P3_CREDENTIALS_0_JWKS: "http://tao-ce-em-auth-server:8080/.well-known/jwks.json",
        DELIVERTENANT_0_LTI_1P3_CREDENTIALS_COUNT: "1",
        DELIVERTENANT_0_LTI_1P3_LAUNCH_URL: "https://%s/deliver/api/v1/auth/launch-lti-1p3" % setup.publicDomain,
        DELIVERTENANT_0_LTI_1P3_OIDC_LOGIN_INITIATION_URL: "https://%s/auth-server/lti1p3/oidc/initiation" % setup.publicDomain,
        DELIVERTENANT_0_OAUTH_CREDENTIALS_0_KEY: "backoffice-deliver-id",
        DELIVERTENANT_0_OAUTH_CREDENTIALS_0_ROLES_0: "Learner",
        DELIVERTENANT_0_OAUTH_CREDENTIALS_0_ROLES_1: "ContentDeveloper",
        DELIVERTENANT_0_OAUTH_CREDENTIALS_0_ROLES_COUNT: "2",
        DELIVERTENANT_0_OAUTH_CREDENTIALS_0_SECRET: "client-secret",
        DELIVERTENANT_0_OAUTH_CREDENTIALS_COUNT: "1",
        DELIVERTENANT_0_ROOT_URL: "http://tao-ce-tao-deliver-be:80/api/v1/",
        DELIVERTENANT_0_TOKEN_URL: "http://tao-ce-em-auth-server:8080/v1/oauth2/tokens",
        DELIVERTENANT_COUNT: "1",
        ELASTICSEARCH_HOSTS: setup.dependencies.es.address.baseUrl,
        FEATURE_FLAG_ENABLE_DATA_STORE_STORAGE: "true",
        FEATURE_FLAG_FLA: "true",
        # FEATURE_FLAG_QUICK_WINS_ENABLED: "true",
        # FEATURE_FLAG_STATISTIC_METADATA_IMPORT: "true",
        FEATURE_FLAG_TAO_ADVANCE_ONLY: "true",
        # FEATURE_FLAG_TRANSLATION_ENABLED: "true",
        # FEATURE_FLAG_UNIQUE_NUMERIC_QTI_IDENTIFIER: "true",
        GOOGLE_CLOUD_DELIVERY_EXECUTION_PUB_SUB_TOPIC_ID: "ss-delivery-executions-topic",
        GOOGLE_CLOUD_DELIVERY_PUB_SUB_TOPIC_ID: "ss-deliveries-topic",
        GOOGLE_CLOUD_PROJECT: setup.env.GOOGLE_CLOUD_PROJECT,
        LTI_AUTHORIZATION_SERVER_FACTORY_ENCRYPTION_KEY: "my-key",
        SCORING_CLIENT_ID: "ss-solar-client-id-for-tao",
        SCORING_CLIENT_SECRET: "secret",
        SCORING_ENABLE: "true",
        SCORING_SCOPE: "event:post",
        SCORING_SERVICE_URL: "http://tao-ce-tao-scoring-service-be:8080/api/v1/events",
        SCORING_TOKEN_URL: "http://tao-ce-em-auth-server:8080/v1/oauth2/tokens",
        XDEBUG_MODE: "off",
    },
    ['%stao-seed' % setup.pfx]: {
        // 'construct-seed.json': std.manifestJson((import './files/seed.libsonnet')(setup)),
        'construct-seed.json': std.manifestJson((import './files/construct-seed.libsonnet')(setup)),
    },
}
