# https://taskfile.dev

version: '3'

method: checksum
output: prefixed
interval: 1s

vars:
  CACHE_DIR: '{{.ROOT_DIR}}/.cache/build'
  ROOT_SIGNAL_DIR: '{{.CACHE_DIR}}/signals'
  REGISTRY: localhost/tao-ce

  SWIFT_IMAGE: tao-ce

  LOCAL_IMAGE: "{{.REGISTRY}}/{{ .SWIFT_IMAGE}}"
  PAYLOAD_IMAGE: "{{.REGISTRY}}/payload/{{ .SWIFT_IMAGE}}"

  BUILD_COMMON_FLAGS: 
    - "--ssh default"
    - "--secret type=file,id=NPM_TOKEN,src={{.ROOT_DIR}}/.secrets/npm"
  TAG: dev-latest

  PAYLOAD_CONTAINERFILE: "{{ .CACHE_DIR }}/artifacts/tao-ce.payload.Containerfile"

  APPS_CONTEXTS:
    map:
      construct: "container-image://{{ .REGISTRY }}/apps/construct:{{ .TAG }}"
      datastore: "container-image://{{ .REGISTRY }}/apps/datastore:{{ .TAG }}"
      deliver: "container-image://{{ .REGISTRY }}/apps/deliver:{{ .TAG }}"
      devkit: "container-image://{{ .REGISTRY }}/apps/devkit:{{ .TAG }}"
      environment-management: "container-image://{{ .REGISTRY }}/apps/environment-management:{{ .TAG }}"
      dynamic-query: "container-image://{{ .REGISTRY }}/apps/dynamic-query:{{ .TAG }}"
      hierarchy: "container-image://{{ .REGISTRY }}/apps/hierarchy:{{ .TAG }}"
      task-orchestrator: "container-image://{{ .REGISTRY }}/apps/task-orchestrator:{{ .TAG }}"
      portal: "container-image://{{ .REGISTRY }}/apps/portal:{{ .TAG }}"
      timers: "container-image://{{ .REGISTRY }}/apps/timers:{{ .TAG }}"

  APPS:
    ref: keys .APPS_CONTEXTS

includes:
  builds:
    taskfile: ./build/Taskfile.builds.yml

  apps:
    taskfile: ./apps/Taskfile.yml

  swift:
    taskfile: ./build/swift

  cozy:
    taskfile: ./build/cozy

  utils:
    taskfile: ./build/utils
    flatten: true

tasks:
  all:clean-start:
    run: once
    cmds:
    - for:
        var: APPS
        as: APP
      task: "apps:{{.APP}}:clean-start"

  all:start:
    deps:
    - for:
        var: APPS
        as: APP
      task: "apps:{{.APP}}:start"

  all:build:
    internal: true
    method: none
    deps:
    - for:
        var: APPS
      task: "apps:{{.ITEM}}:build"

  all:up:
    method: none
    deps:
    - for:
        var: APPS
      task: "apps:{{.ITEM}}:up"
    

  dev:wipe:
    desc: Remove all persistent data and config
    ignore_error: true
    prompt:
    - This task will wipe all data from ElasticSearch, do you want to continue?
    - This task will wipe all data from /var/lib/tao-ce, do you want to continue?
    - This task will wipe all data from /etc/tao-ce/setup, do you want to continue?
    cmds:
    - sudo bash /etc/tao-ce/setup/scripts/wipe/es.sh
    - sudo bash /etc/tao-ce/setup/scripts/wipe/data.sh
    - sudo bash /etc/tao-ce/setup/scripts/wipe/config.sh
    - rm -rf {{.ROOT_SIGNAL_DIR}}/apps/*/*/start/*

  dev:down:
    desc: stop all tao-ce services and clean /opt/tao-ce 
    ignore_error: true
    prompt:
    - This task will wipe all code from devcontainer, do you want to continue?
    cmds:
    - sudo systemctl stop --no-warn "tao-ce.*.service"
    - sudo systemctl disable --no-warn "tao-ce.*.service"
    - task: dev:wipe
    - sudo rm -rf /opt/tao-ce/* /etc/tao-ce
    - rm -rf {{.ROOT_SIGNAL_DIR}}/apps/*/*/deploy
    - rm -rf {{.ROOT_SIGNAL_DIR}}/apps/*/*/start

  dev:setup:
    desc: restart core services
    method: none
    sources:
      - ./etc/tao-ce
      - ./libexec/init
      - ./libexec/setup

    deps: [dev:sync:etc, dev:sync:libexec]
    cmds:
    - sudo systemctl enable --force /usr/local/libexec/tao-ce/systemd/tao-ce.target
    - sudo systemctl enable --force /usr/local/libexec/tao-ce/systemd/tao-ce.setup.service
    - sudo systemctl enable --force /usr/local/libexec/tao-ce/systemd/tao-ce.static.service
    - sudo systemctl restart tao-ce.setup.service
    - sudo systemctl restart tao-ce.static.service

  dev:sync:etc:
    desc: copy etc config files
    method: none
    sources:
    - ./etc/**
    - ./build/crystal/etc/**
    cmds:
    - sudo cp -va ./etc/* /etc/
    - sudo cp -va ./build/crystal/etc/* /etc/

  dev:sync:libexec:
    desc: copy libexec files
    method: none
    sources:
    - ./libexec/**
    cmds:
    - sudo mkdir -p /usr/local/libexec/tao-ce
    - sudo cp -va ./libexec/* /usr/local/libexec/tao-ce/

  dev:logdy:
    desc: refresh config and start logdy
    sources:
      - ./build/crystal/etc/logdy.config.json
      - ./build/crystal/etc/systemd/system/logdy.service
    deps: [dev:sync:etc, dev:sync:libexec]
    cmds:
      - sudo systemctl daemon-reload
      - sudo systemctl enable --force /etc/systemd/system/logdy.service
      - sudo systemctl restart logdy.service

  dev:init:
    desc: initialize dev environment
    method: none
    cmds:
    - task: dev:logdy
    - task: dev:setup

  dev:up:
    desc: Start all applications, and watch for changes

    method: none

    sources:
      - ./apps/**
      - exclude: .task/**

    deps:
    - task: dev:init
    - task: builds:base:build
    - task: builds:go:build
    cmds:
    - task: _log
      vars:
        MESSAGE: "Updating all apps..."
        APP: "@all"
    - task: all:up
    - task: _log
      vars:
        MESSAGE: "Apps update done"
        APP: "@all"

  dev:prune:
    desc: Remove building cache
    cmds:
    - buildah prune -af
    - buildah rm -a
    - podman system reset -f
    - rm -rf {{.ROOT_SIGNAL_DIR}} .task .cache