#!/bin/sh
#

DEFAULT_INIT_MANIFEST=${PWD}
DEVCONTAINER_INIT_MANIFEST=${DEVCONTAINER_INIT_MANIFEST:-${DEFAULT_INIT_MANIFEST}}

[ -n "$DEVCONTAINER_FLAVOR" ] && make ${DEVCONTAINER_FLAVOR}

[  -f ${DEVCONTAINER_INIT_MANIFEST}/kustomization.yaml \
-o -f ${DEVCONTAINER_INIT_MANIFEST}/kustomization.yml  \
] && {
    kubectl kustomize ${DEVCONTAINER_INIT_MANIFEST} \
        | sudo tee ${K3S_MANIFESTS}/devcontainer-init.yaml
} || {
    echo No manifest found at ${DEVCONTAINER_INIT_MANIFEST}, skipping >&2
}
