#!/bin/sh
#

. ${TAOADM_CONFIG}/config.inc.sh
. ${TAOADM_LIBEXEC}/common.inc.sh

. ${TAOADM_CONFIG}/apps/construct.inc.sh
. ${TAOADM_LIBEXEC}/apps/construct.inc.sh

# entrypoint need to adjust some permission as root
[ $(id -u) -eq 0 ] && {
    construct_init
}

cmd=$1
[ -n "${cmd}" ] && shift 1 || cmd=run
case $cmd in
    run)
        construct_run $@
        ;;
    worker)
        construct_worker $@
        ;;
    install)
        construct_install $@
        ;;
    update)
        construct_update $@
        ;;
esac


