ARG BASE="build/node"

FROM ${BASE} AS export 

WORKDIR /app

ENV API_URL=/data
ARG PORT=3000

COPY ./package*.json .

RUN --mount=type=secret,id=NPM_TOKEN \
    --mount=type=cache,id=npm-cache,target=/root/.npm \
    npm  config set //registry.npmjs.org/:_authToken=$(cat /run/secrets/NPM_TOKEN) && npm whoami
COPY . .
RUN --mount=type=cache,id=npm-cache,target=/root/.npm npm ci 
RUN --mount=type=cache,id=npm-cache,target=/root/.npm npm run build

CMD ["npm", "start"]