
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: es
  name: es
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    io.kompose.service: es

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
spec:
  resources:
    requests:
      storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: es
  name: es
spec:
  serviceName: es
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es
  template:
    metadata:
      labels:
        io.kompose.service: es
    spec:
      initContainers:
        - name: fix-ownership
          image: alpine
          command:
            - /bin/sh
            - -c
            - |
              chown -R 1000:1000 /usr/share/elasticsearch/data
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      containers:
        - env:
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: ES_JAVA_OPTS
              value: -Xms128m -Xmx1024m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: node.name
              value: es
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
            - name: xpack.watcher.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  curl -fs http://es:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 30
          name: es
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      restartPolicy: Always
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data