---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: pgsql
  name: pgsql
spec:
  serviceName: pgsql
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgsql
  template:
    metadata:
      labels:
        io.kompose.service: pgsql
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /data/pg
          image: docker.io/postgres:17-alpine
          name: pgsql
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: pgsql-data
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            claimName: pgsql-data
          name: pgsql-data

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pgsql
  name: pgsql
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: pgsql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-data
spec:
  resources:
    requests:
      storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce