# syntax=docker/dockerfile:1-labs

ARG BUILD_IMAGE
ARG BUILD_NPM_REGISTRY

 ## backend ####################################################################
FROM $BUILD_IMAGE AS build-backend
ARG BUILD_IMAGE
ARG STATE_ROOT="/var/lib/tao-ce/content-service"
ENV STATE_ROOT=$STATE_ROOT

ENV NODE_ENV=production

WORKDIR /app

COPY --from=src-backend . .

#include <npm/ci.in>
RUN <<EORUN
    set -eux
    rm -rf node_modules/@opentelemetry
    echo 'export const shutdownOtel = () => {};' >src/instrumentation/otel.js  #https://github.com/oat-sa/tao-content-service/pull/203
    STATE_DATA(data,var)
EORUN
#include <clean-app.in>

 ## Export #####################################################################
FROM scratch AS export

COPY --link --from=build-backend \
    /app /backend

COPY meta /meta
