PWD = os.getcwd()

ARTIFACTS = {
    'service/pubsub-cli': 'service/pubsub-cli',
}



# def pull(builder):
    # builder['pull']()

def build(builder):
    build = builder['build']
    
    build(
        ref=ARTIFACTS['service/pubsub-cli'],
        context='{}/pubsub-cli'.format(PWD),
        target='export',
        )