# syntax=docker/dockerfile:1-labs

ARG BUILD_IMAGE

 ## backend ####################################################################
FROM $BUILD_IMAGE AS build-backend
ARG BUILD_IMAGE
ARG STATE_ROOT="/var/lib/tao-ce/devkit"

WORKDIR /app
COPY  --from=src-backend . .

#include <composer/install.in>
#include <clean-app.in>

RUN <<EORUN
    STATE_DATA(data,var)
    STATE_DATA(config/keys,config/keys)
    STATE_FILE(config/packages/lti1p3.yaml,config/packages/lti1p3.yaml)
EORUN

 ## Export #####################################################################
FROM scratch AS export

COPY --link --from=build-backend \
        /app /backend
COPY ./router.php /backend/router.php

COPY meta /meta