function(setup)

  {
    tenants: [
      {
        configurations: [
          {
            name: 'testRunnerConfiguration',
            value: {
              exportProviders: {
                itemRunner: {
                  category: 'runner',
                  id: 'qtinui',
                  module: 'taoQtiNuiItem/runner/qti',
                },
                plugins: [
                  {
                    category: 'content',
                    id: 'bookletExportPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/export/bookletExport/plugin',
                  },
                  {
                    category: 'content',
                    id: 'navigatorPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/navigation/reviewNavigator/plugin',
                  },
                ],
                proxy: {
                  category: 'proxy',
                  id: 'actions-proxy',
                  module: 'taoQtiNuiTest/runner/proxy/actionProxy',
                },
                runner: {
                  category: 'runner',
                  id: 'qtinuiExport',
                  module: 'taoQtiNuiTest/runner/qtiExport',
                },
              },
              options: {
                itemRunnerConfig: {
                  elements: {
                    CustomInteraction_audioRecordingInteraction: {
                      propertyOverride: {
                        useUploader: true,
                      },
                    },
                    ExtendedTextInteraction: {
                      propertyOverride: {
                        dataAttrs: {
                          'data-image-upload': 'true',
                          'data-math-entry-keyboards': 'custom1 roman',
                          'data-special-characters': 'latinAndMaths',
                          'data-word-count': 'true',
                        },
                        uploadMaxSize: 15000000,
                        uploadTimeout: 300000,
                      },
                    },
                    GraphicGapMatchInteraction: {
                      qtiClassesOverride: [
                        'qti-unselected-hidden',
                      ],
                    },
                    HotspotInteraction: {
                      qtiClassesOverride: [
                        'qti-unselected-hidden',
                      ],
                    },
                    HottextInteraction: {
                      qtiClassesOverride: [
                        'tao-control-styling-hidden',
                      ],
                    },
                    Include: {
                      qtiClassesOverride: [
                        'tao-immediate-scroll',
                      ],
                    },
                    UploadInteraction: {
                      propertyOverride: {
                        maxSize: 100000000,
                        timeout: 1800000,
                      },
                    },
                  },
                },
                liteMode: false,
                plugins: {
                  localItemState: {
                    saveState: {
                      enabled: true,
                      excludePciTypeIdentifiers: [
                        'audioRecordingInteraction',
                      ],
                      liveSaveIndicator: {
                        enabled: true,
                      },
                      maxWait: 20000,
                      minWait: 5000,
                    },
                  },
                  preloadNextItemAssets: {
                    preloadStrategy: {
                      audios: true,
                      audiosThreshold: 3000000,
                      images: true,
                      stylesheets: true,
                      videos: true,
                      videosThreshold: 3000000,
                    },
                  },
                  readAloud: {
                    providerId: 'native',
                  },
                  scratchpad: {
                    enableStateActions: true,
                    tools: [
                      {
                        enabled: true,
                        key: 'select',
                      },
                      {
                        enabled: true,
                        key: 'text',
                      },
                      {
                        enabled: true,
                        key: 'brush',
                      },
                      {
                        enabled: true,
                        key: 'rectangle',
                      },
                      {
                        enabled: true,
                        key: 'eraser',
                      },
                    ],
                  },
                },
                proxy: {
                  preloadItemStoreCapacity: 30,
                  preloadSectionItemsAmount: 5,
                  preloadStrategy: 'nextItem',
                },
                realTimeService: {
                  enabled: true,
                  socketConnectionUrl: 'https://%s/timers' % [setup.publicDomain],
                },
              },
              providers: {
                itemRunner: {
                  category: 'runner',
                  id: 'qtinui',
                  module: 'taoQtiNuiItem/runner/qti',
                },
                plugins: [
                  {
                    category: 'content',
                    id: 'titlePlugin',
                    module: 'taoQtiNuiTest/runner/plugins/content/title/plugin',
                  },
                  {
                    category: 'content',
                    id: 'menuPanelPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/panel/menu/plugin',
                  },
                  {
                    category: 'content',
                    id: 'jumpMenuPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/navigation/jumpMenu/plugin',
                  },
                  {
                    category: 'content',
                    id: 'navigatorPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/navigation/navigator/plugin',
                  },
                  {
                    category: 'settings',
                    id: 'settingsPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/settings/plugin',
                  },
                  {
                    category: 'state',
                    id: 'localItemState',
                    module: 'taoQtiNuiTest/runner/plugins/localItemState/plugin',
                  },
                  {
                    category: 'tools',
                    id: 'scratchpad',
                    module: 'taoQtiNuiTest/runner/plugins/tools/scratchpad/plugin',
                  },
                  {
                    category: 'tools',
                    id: 'highlighter',
                    module: 'taoQtiNuiTest/runner/plugins/tools/highlighter/plugin',
                  },
                  {
                    category: 'tools',
                    id: 'readAloud',
                    module: 'taoQtiNuiTest/runner/plugins/tools/readAloud/plugin',
                  },
                  {
                    category: 'performance',
                    id: 'preloadNextItemAssetsPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/navigation/preload/nextItemAssets/plugin',
                  },
                  {
                    category: 'tools',
                    id: 'lineReader',
                    module: 'taoQtiNuiTest/runner/plugins/tools/lineReader/plugin',
                  },
                  {
                    category: 'tools',
                    id: 'fullscreen',
                    module: 'taoQtiNuiTest/runner/plugins/tools/fullscreen/plugin',
                  },
                  {
                    category: 'navigation',
                    id: 'warnBeforeLeaving',
                    module: 'taoQtiNuiTest/runner/plugins/navigation/warnBeforeLeaving/plugin',
                  },
                  {
                    category: 'navigation',
                    id: 'proctoring',
                    module: 'taoQtiNuiTest/runner/plugins/proctoring/plugin',
                  },
                  {
                    category: 'navigation',
                    id: 'PCINavigationHelper',
                    module: 'taoQtiNuiTest/runner/plugins/navigation/PCINavigationHelper/plugin',
                  },
                ],
                proxy: {
                  category: 'proxy',
                  id: 'preload-actions-proxy',
                  module: 'taoQtiNuiTest/runner/proxy/preloadProxy',
                },
                runner: {
                  category: 'runner',
                  id: 'qtinui',
                  module: 'taoQtiNuiTest/runner/qti',
                },
              },
              reviewProviders: {
                itemRunner: {
                  category: 'runner',
                  id: 'qtinui',
                  module: 'taoQtiNuiItem/runner/qti',
                },
                plugins: [
                  {
                    category: 'content',
                    id: 'titlePlugin',
                    module: 'taoQtiNuiTest/runner/plugins/content/title/plugin',
                  },
                  {
                    category: 'content',
                    id: 'menuPanelPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/panel/menu/plugin',
                  },
                  {
                    category: 'content',
                    id: 'navigatorPlugin',
                    module: 'taoQtiNuiTest/runner/plugins/navigation/reviewNavigator/plugin',
                  },
                  {
                    category: 'integration',
                    id: 'notify',
                    module: 'taoQtiNuiTest/runner/plugins/integration/notify/plugin',
                  },
                  {
                    category: 'tools',
                    id: 'highlighter',
                    module: 'taoQtiNuiTest/runner/plugins/tools/highlighter/plugin',
                  },
                ],
                proxy: {
                  category: 'proxy',
                  id: 'review-proxy',
                  module: 'taoQtiNuiTest/runner/proxy/reviewProxy',
                },
                runner: {
                  category: 'runner',
                  id: 'qtinui',
                  module: 'taoQtiNuiTest/runner/qtiReview',
                },
              },
            },
          },
            {
              name: 'AUTH_MODE',
              value: 'sessionStorage',
            },
          {
            name: 'deliver-launch-claims',
            value: std.toString({
              "https://purl.imsglobal.org/spec/lti/claim/roles": [
                "http://purl.imsglobal.org/vocab/lis/v2/membership#Learner"
              ],
              "https://purl.imsglobal.org/spec/lti/claim/custom": {
                "deliverySettings.review.deliveryExecutionId": "<<deliveryExecutionId>>",
              },
              "sub": "<<sub>>",
            }),
          },
          {
            name: 'editorConfiguration',
            value: {
              accessTokenTTL: 500000,
              locale: setup.defaultLocale,
              routes: {
                'error': '/error',
                splash: '/',
                testEditor: '/test-editor/',
              },
              runnerConfiguration: {
                options: {
                  itemRunnerConfig: {},
                  plugins: {},
                  proxy: {
                    retryInterval: 5000,
                    retryTimeout: 120000,
                  },
                },
                providers: {
                  itemRunner: {
                    category: 'runner',
                    id: 'qtiItemEditor',
                    module: 'taoQtiNuiTestEditor/item-runner/qtiItemEditor',
                  },
                  plugins: [
                    {
                      category: 'navigation',
                      id: 'navigatorPlugin',
                      module: 'taoQtiNuiTestEditor/test-runner/plugins/navigator/plugin',
                    },
                    {
                      category: 'authoring',
                      id: 'itemAuthoring',
                      module: 'taoQtiNuiTestEditor/test-runner/plugins/itemAuthoring/plugin',
                    },
                  ],
                  proxy: {
                    category: 'proxy',
                    id: 'qtiTestEditorProxy',
                    module: 'taoQtiNuiTestEditor/test-runner/proxy/testEditorProxy',
                  },
                  runner: {
                    category: 'runner',
                    id: 'qtiTestEditor',
                    module: 'taoQtiNuiTestEditor/test-runner/qtiTestEditor',
                  },
                },
                themes: {
                  platform: {
                    favicon: {
                      href: 'favicon.ico',
                      type: 'image/x-icon',
                    },
                    title: 'TAO Studio - Test Editor',
                  },
                },
              },
            },
          },
          {
            name: 'deliver_type',
            value: 'DeliverSolar',
          },
          {
            name: 'testRunnerTheme',
            value: {
              default: 'default',
              itemRunner: [
                'itemRunner',
              ],
              platform: {
                favicon: {
                  href: 'favicon.ico',
                  type: 'image/x-icon',
                },
              },
              testRunner: {
                showUserMenu: true,
              },
            },
          },
          {
            name: 'MSConfiguration',
            value: {
              static_url: 'https://%s/ms-fe' % [setup.publicDomain],
            },
          },
          {
            name: 'portal.support',
            value: {
              tabs: {
                'activity-logs': {
                  description: 'Activity logs',
                  fields: [
                    'userName',
                    'userId',
                    'tenantId',
                    'success',
                    'personalData',
                    'messageId',
                    'eventTimestamp',
                    'eventId',
                    'errorDetails',
                    'entityType',
                    'entityId',
                    'component',
                    'action',
                  ],
                },
                'delivery-executions': {
                  description: 'Delivery executions',
                  fields: [
                    'deliveryExecutionId',
                    'status',
                    'startTime',
                    'finishTime',
                  ],
                },
                'live-activity': {},
                password: {},
                'proctoring-logs': {
                  description: 'Proctoring logs',
                  fields: [
                    'actor',
                    'login',
                    'deliveryExecutionId',
                    'itemId',
                    'deliveryId',
                    'status',
                    'action',
                    'actionStatus',
                    'incidentTime',
                    'attemptNumber',
                    'last_update_date',
                  ],
                },
                'test-results': {
                  description: 'Test results',
                  fields: [
                    'thetaScore',
                    'testQtiTitle',
                    'testQtiLabel',
                    'tenantId',
                    'submissionTime',
                    'sessionStartTime',
                    'sessionEndTime',
                  ],
                },
                'user-sessions': {
                  description: 'User sessions',
                  fields: [
                    'deliveryExecutionId',
                    'deliveryExecutionStatus',
                    'deliveryGradingStatus',
                  ],
                },
              },
            },
          },
          {
            name: 'portal.countries',
            value: [
              {
                alpha2: 'af',
                alpha3: 'afg',
                id: 4,
                name: 'Afghanistan',
              },
              {
                alpha2: 'al',
                alpha3: 'alb',
                id: 8,
                name: 'Albania',
              },
              {
                alpha2: 'dz',
                alpha3: 'dza',
                id: 12,
                name: 'Algeria',
              },
              {
                alpha2: 'ad',
                alpha3: 'and',
                id: 20,
                name: 'Andorra',
              },
              {
                alpha2: 'ao',
                alpha3: 'ago',
                id: 24,
                name: 'Angola',
              },
              {
                alpha2: 'ag',
                alpha3: 'atg',
                id: 28,
                name: 'Antigua and Barbuda',
              },
              {
                alpha2: 'ar',
                alpha3: 'arg',
                id: 32,
                name: 'Argentina',
              },
              {
                alpha2: 'am',
                alpha3: 'arm',
                id: 51,
                name: 'Armenia',
              },
              {
                alpha2: 'au',
                alpha3: 'aus',
                id: 36,
                name: 'Australia',
              },
              {
                alpha2: 'at',
                alpha3: 'aut',
                id: 40,
                name: 'Austria',
              },
              {
                alpha2: 'az',
                alpha3: 'aze',
                id: 31,
                name: 'Azerbaijan',
              },
              {
                alpha2: 'bs',
                alpha3: 'bhs',
                id: 44,
                name: 'Bahamas',
              },
              {
                alpha2: 'bh',
                alpha3: 'bhr',
                id: 48,
                name: 'Bahrain',
              },
              {
                alpha2: 'bd',
                alpha3: 'bgd',
                id: 50,
                name: 'Bangladesh',
              },
              {
                alpha2: 'bb',
                alpha3: 'brb',
                id: 52,
                name: 'Barbados',
              },
              {
                alpha2: 'by',
                alpha3: 'blr',
                id: 112,
                name: 'Belarus',
              },
              {
                alpha2: 'be',
                alpha3: 'bel',
                id: 56,
                name: 'Belgium',
              },
              {
                alpha2: 'bz',
                alpha3: 'blz',
                id: 84,
                name: 'Belize',
              },
              {
                alpha2: 'bj',
                alpha3: 'ben',
                id: 204,
                name: 'Benin',
              },
              {
                alpha2: 'bt',
                alpha3: 'btn',
                id: 64,
                name: 'Bhutan',
              },
              {
                alpha2: 'bo',
                alpha3: 'bol',
                id: 68,
                name: 'Bolivia, Plurinational State of',
              },
              {
                alpha2: 'ba',
                alpha3: 'bih',
                id: 70,
                name: 'Bosnia and Herzegovina',
              },
              {
                alpha2: 'bw',
                alpha3: 'bwa',
                id: 72,
                name: 'Botswana',
              },
              {
                alpha2: 'br',
                alpha3: 'bra',
                id: 76,
                name: 'Brazil',
              },
              {
                alpha2: 'bn',
                alpha3: 'brn',
                id: 96,
                name: 'Brunei Darussalam',
              },
              {
                alpha2: 'bg',
                alpha3: 'bgr',
                id: 100,
                name: 'Bulgaria',
              },
              {
                alpha2: 'bf',
                alpha3: 'bfa',
                id: 854,
                name: 'Burkina Faso',
              },
              {
                alpha2: 'bi',
                alpha3: 'bdi',
                id: 108,
                name: 'Burundi',
              },
              {
                alpha2: 'cv',
                alpha3: 'cpv',
                id: 132,
                name: 'Cabo Verde',
              },
              {
                alpha2: 'kh',
                alpha3: 'khm',
                id: 116,
                name: 'Cambodia',
              },
              {
                alpha2: 'cm',
                alpha3: 'cmr',
                id: 120,
                name: 'Cameroon',
              },
              {
                alpha2: 'ca',
                alpha3: 'can',
                id: 124,
                name: 'Canada',
              },
              {
                alpha2: 'cf',
                alpha3: 'caf',
                id: 140,
                name: 'Central African Republic',
              },
              {
                alpha2: 'td',
                alpha3: 'tcd',
                id: 148,
                name: 'Chad',
              },
              {
                alpha2: 'cl',
                alpha3: 'chl',
                id: 152,
                name: 'Chile',
              },
              {
                alpha2: 'cn',
                alpha3: 'chn',
                id: 156,
                name: 'China',
              },
              {
                alpha2: 'co',
                alpha3: 'col',
                id: 170,
                name: 'Colombia',
              },
              {
                alpha2: 'km',
                alpha3: 'com',
                id: 174,
                name: 'Comoros',
              },
              {
                alpha2: 'cg',
                alpha3: 'cog',
                id: 178,
                name: 'Congo',
              },
              {
                alpha2: 'cd',
                alpha3: 'cod',
                id: 180,
                name: 'Congo, Democratic Republic of the',
              },
              {
                alpha2: 'cr',
                alpha3: 'cri',
                id: 188,
                name: 'Costa Rica',
              },
              {
                alpha2: 'ci',
                alpha3: 'civ',
                id: 384,
                name: "Côte d'Ivoire",
              },
              {
                alpha2: 'hr',
                alpha3: 'hrv',
                id: 191,
                name: 'Croatia',
              },
              {
                alpha2: 'cu',
                alpha3: 'cub',
                id: 192,
                name: 'Cuba',
              },
              {
                alpha2: 'cy',
                alpha3: 'cyp',
                id: 196,
                name: 'Cyprus',
              },
              {
                alpha2: 'cz',
                alpha3: 'cze',
                id: 203,
                name: 'Czechia',
              },
              {
                alpha2: 'dk',
                alpha3: 'dnk',
                id: 208,
                name: 'Denmark',
              },
              {
                alpha2: 'dj',
                alpha3: 'dji',
                id: 262,
                name: 'Djibouti',
              },
              {
                alpha2: 'dm',
                alpha3: 'dma',
                id: 212,
                name: 'Dominica',
              },
              {
                alpha2: 'do',
                alpha3: 'dom',
                id: 214,
                name: 'Dominican Republic',
              },
              {
                alpha2: 'ec',
                alpha3: 'ecu',
                id: 218,
                name: 'Ecuador',
              },
              {
                alpha2: 'eg',
                alpha3: 'egy',
                id: 818,
                name: 'Egypt',
              },
              {
                alpha2: 'sv',
                alpha3: 'slv',
                id: 222,
                name: 'El Salvador',
              },
              {
                alpha2: 'gq',
                alpha3: 'gnq',
                id: 226,
                name: 'Equatorial Guinea',
              },
              {
                alpha2: 'er',
                alpha3: 'eri',
                id: 232,
                name: 'Eritrea',
              },
              {
                alpha2: 'ee',
                alpha3: 'est',
                id: 233,
                name: 'Estonia',
              },
              {
                alpha2: 'sz',
                alpha3: 'swz',
                id: 748,
                name: 'Eswatini',
              },
              {
                alpha2: 'et',
                alpha3: 'eth',
                id: 231,
                name: 'Ethiopia',
              },
              {
                alpha2: 'fj',
                alpha3: 'fji',
                id: 242,
                name: 'Fiji',
              },
              {
                alpha2: 'fi',
                alpha3: 'fin',
                id: 246,
                name: 'Finland',
              },
              {
                alpha2: 'fr',
                alpha3: 'fra',
                id: 250,
                name: 'France',
              },
              {
                alpha2: 'ga',
                alpha3: 'gab',
                id: 266,
                name: 'Gabon',
              },
              {
                alpha2: 'gm',
                alpha3: 'gmb',
                id: 270,
                name: 'Gambia',
              },
              {
                alpha2: 'ge',
                alpha3: 'geo',
                id: 268,
                name: 'Georgia',
              },
              {
                alpha2: 'de',
                alpha3: 'deu',
                id: 276,
                name: 'Germany',
              },
              {
                alpha2: 'gh',
                alpha3: 'gha',
                id: 288,
                name: 'Ghana',
              },
              {
                alpha2: 'gr',
                alpha3: 'grc',
                id: 300,
                name: 'Greece',
              },
              {
                alpha2: 'gd',
                alpha3: 'grd',
                id: 308,
                name: 'Grenada',
              },
              {
                alpha2: 'gt',
                alpha3: 'gtm',
                id: 320,
                name: 'Guatemala',
              },
              {
                alpha2: 'gn',
                alpha3: 'gin',
                id: 324,
                name: 'Guinea',
              },
              {
                alpha2: 'gw',
                alpha3: 'gnb',
                id: 624,
                name: 'Guinea-Bissau',
              },
              {
                alpha2: 'gy',
                alpha3: 'guy',
                id: 328,
                name: 'Guyana',
              },
              {
                alpha2: 'ht',
                alpha3: 'hti',
                id: 332,
                name: 'Haiti',
              },
              {
                alpha2: 'hn',
                alpha3: 'hnd',
                id: 340,
                name: 'Honduras',
              },
              {
                alpha2: 'hu',
                alpha3: 'hun',
                id: 348,
                name: 'Hungary',
              },
              {
                alpha2: 'is',
                alpha3: 'isl',
                id: 352,
                name: 'Iceland',
              },
              {
                alpha2: 'in',
                alpha3: 'ind',
                id: 356,
                name: 'India',
              },
              {
                alpha2: 'id',
                alpha3: 'idn',
                id: 360,
                name: 'Indonesia',
              },
              {
                alpha2: 'ir',
                alpha3: 'irn',
                id: 364,
                name: 'Iran, Islamic Republic of',
              },
              {
                alpha2: 'iq',
                alpha3: 'irq',
                id: 368,
                name: 'Iraq',
              },
              {
                alpha2: 'ie',
                alpha3: 'irl',
                id: 372,
                name: 'Ireland',
              },
              {
                alpha2: 'il',
                alpha3: 'isr',
                id: 376,
                name: 'Israel',
              },
              {
                alpha2: 'it',
                alpha3: 'ita',
                id: 380,
                name: 'Italy',
              },
              {
                alpha2: 'jm',
                alpha3: 'jam',
                id: 388,
                name: 'Jamaica',
              },
              {
                alpha2: 'jp',
                alpha3: 'jpn',
                id: 392,
                name: 'Japan',
              },
              {
                alpha2: 'jo',
                alpha3: 'jor',
                id: 400,
                name: 'Jordan',
              },
              {
                alpha2: 'kz',
                alpha3: 'kaz',
                id: 398,
                name: 'Kazakhstan',
              },
              {
                alpha2: 'ke',
                alpha3: 'ken',
                id: 404,
                name: 'Kenya',
              },
              {
                alpha2: 'ki',
                alpha3: 'kir',
                id: 296,
                name: 'Kiribati',
              },
              {
                alpha2: 'kp',
                alpha3: 'prk',
                id: 408,
                name: "Korea, Democratic People's Republic of",
              },
              {
                alpha2: 'kr',
                alpha3: 'kor',
                id: 410,
                name: 'Korea, Republic of',
              },
              {
                alpha2: 'kw',
                alpha3: 'kwt',
                id: 414,
                name: 'Kuwait',
              },
              {
                alpha2: 'kg',
                alpha3: 'kgz',
                id: 417,
                name: 'Kyrgyzstan',
              },
              {
                alpha2: 'la',
                alpha3: 'lao',
                id: 418,
                name: "Lao People's Democratic Republic",
              },
              {
                alpha2: 'lv',
                alpha3: 'lva',
                id: 428,
                name: 'Latvia',
              },
              {
                alpha2: 'lb',
                alpha3: 'lbn',
                id: 422,
                name: 'Lebanon',
              },
              {
                alpha2: 'ls',
                alpha3: 'lso',
                id: 426,
                name: 'Lesotho',
              },
              {
                alpha2: 'lr',
                alpha3: 'lbr',
                id: 430,
                name: 'Liberia',
              },
              {
                alpha2: 'ly',
                alpha3: 'lby',
                id: 434,
                name: 'Libya',
              },
              {
                alpha2: 'li',
                alpha3: 'lie',
                id: 438,
                name: 'Liechtenstein',
              },
              {
                alpha2: 'lt',
                alpha3: 'ltu',
                id: 440,
                name: 'Lithuania',
              },
              {
                alpha2: 'lu',
                alpha3: 'lux',
                id: 442,
                name: 'Luxembourg',
              },
              {
                alpha2: 'mg',
                alpha3: 'mdg',
                id: 450,
                name: 'Madagascar',
              },
              {
                alpha2: 'mw',
                alpha3: 'mwi',
                id: 454,
                name: 'Malawi',
              },
              {
                alpha2: 'my',
                alpha3: 'mys',
                id: 458,
                name: 'Malaysia',
              },
              {
                alpha2: 'mv',
                alpha3: 'mdv',
                id: 462,
                name: 'Maldives',
              },
              {
                alpha2: 'ml',
                alpha3: 'mli',
                id: 466,
                name: 'Mali',
              },
              {
                alpha2: 'mt',
                alpha3: 'mlt',
                id: 470,
                name: 'Malta',
              },
              {
                alpha2: 'mh',
                alpha3: 'mhl',
                id: 584,
                name: 'Marshall Islands',
              },
              {
                alpha2: 'mr',
                alpha3: 'mrt',
                id: 478,
                name: 'Mauritania',
              },
              {
                alpha2: 'mu',
                alpha3: 'mus',
                id: 480,
                name: 'Mauritius',
              },
              {
                alpha2: 'mx',
                alpha3: 'mex',
                id: 484,
                name: 'Mexico',
              },
              {
                alpha2: 'fm',
                alpha3: 'fsm',
                id: 583,
                name: 'Micronesia, Federated States of',
              },
              {
                alpha2: 'md',
                alpha3: 'mda',
                id: 498,
                name: 'Moldova, Republic of',
              },
              {
                alpha2: 'mc',
                alpha3: 'mco',
                id: 492,
                name: 'Monaco',
              },
              {
                alpha2: 'mn',
                alpha3: 'mng',
                id: 496,
                name: 'Mongolia',
              },
              {
                alpha2: 'me',
                alpha3: 'mne',
                id: 499,
                name: 'Montenegro',
              },
              {
                alpha2: 'ma',
                alpha3: 'mar',
                id: 504,
                name: 'Morocco',
              },
              {
                alpha2: 'mz',
                alpha3: 'moz',
                id: 508,
                name: 'Mozambique',
              },
              {
                alpha2: 'mm',
                alpha3: 'mmr',
                id: 104,
                name: 'Myanmar',
              },
              {
                alpha2: 'na',
                alpha3: 'nam',
                id: 516,
                name: 'Namibia',
              },
              {
                alpha2: 'nr',
                alpha3: 'nru',
                id: 520,
                name: 'Nauru',
              },
              {
                alpha2: 'np',
                alpha3: 'npl',
                id: 524,
                name: 'Nepal',
              },
              {
                alpha2: 'nl',
                alpha3: 'nld',
                id: 528,
                name: 'Netherlands',
              },
              {
                alpha2: 'nz',
                alpha3: 'nzl',
                id: 554,
                name: 'New Zealand',
              },
              {
                alpha2: 'ni',
                alpha3: 'nic',
                id: 558,
                name: 'Nicaragua',
              },
              {
                alpha2: 'ne',
                alpha3: 'ner',
                id: 562,
                name: 'Niger',
              },
              {
                alpha2: 'ng',
                alpha3: 'nga',
                id: 566,
                name: 'Nigeria',
              },
              {
                alpha2: 'mk',
                alpha3: 'mkd',
                id: 807,
                name: 'North Macedonia',
              },
              {
                alpha2: 'no',
                alpha3: 'nor',
                id: 578,
                name: 'Norway',
              },
              {
                alpha2: 'om',
                alpha3: 'omn',
                id: 512,
                name: 'Oman',
              },
              {
                alpha2: 'pk',
                alpha3: 'pak',
                id: 586,
                name: 'Pakistan',
              },
              {
                alpha2: 'pw',
                alpha3: 'plw',
                id: 585,
                name: 'Palau',
              },
              {
                alpha2: 'pa',
                alpha3: 'pan',
                id: 591,
                name: 'Panama',
              },
              {
                alpha2: 'pg',
                alpha3: 'png',
                id: 598,
                name: 'Papua New Guinea',
              },
              {
                alpha2: 'py',
                alpha3: 'pry',
                id: 600,
                name: 'Paraguay',
              },
              {
                alpha2: 'pe',
                alpha3: 'per',
                id: 604,
                name: 'Peru',
              },
              {
                alpha2: 'ph',
                alpha3: 'phl',
                id: 608,
                name: 'Philippines',
              },
              {
                alpha2: 'pl',
                alpha3: 'pol',
                id: 616,
                name: 'Poland',
              },
              {
                alpha2: 'pt',
                alpha3: 'prt',
                id: 620,
                name: 'Portugal',
              },
              {
                alpha2: 'qa',
                alpha3: 'qat',
                id: 634,
                name: 'Qatar',
              },
              {
                alpha2: 'ro',
                alpha3: 'rou',
                id: 642,
                name: 'Romania',
              },
              {
                alpha2: 'ru',
                alpha3: 'rus',
                id: 643,
                name: 'Russian Federation',
              },
              {
                alpha2: 'rw',
                alpha3: 'rwa',
                id: 646,
                name: 'Rwanda',
              },
              {
                alpha2: 'kn',
                alpha3: 'kna',
                id: 659,
                name: 'Saint Kitts and Nevis',
              },
              {
                alpha2: 'lc',
                alpha3: 'lca',
                id: 662,
                name: 'Saint Lucia',
              },
              {
                alpha2: 'vc',
                alpha3: 'vct',
                id: 670,
                name: 'Saint Vincent and the Grenadines',
              },
              {
                alpha2: 'ws',
                alpha3: 'wsm',
                id: 882,
                name: 'Samoa',
              },
              {
                alpha2: 'sm',
                alpha3: 'smr',
                id: 674,
                name: 'San Marino',
              },
              {
                alpha2: 'st',
                alpha3: 'stp',
                id: 678,
                name: 'Sao Tome and Principe',
              },
              {
                alpha2: 'sa',
                alpha3: 'sau',
                id: 682,
                name: 'Saudi Arabia',
              },
              {
                alpha2: 'sn',
                alpha3: 'sen',
                id: 686,
                name: 'Senegal',
              },
              {
                alpha2: 'rs',
                alpha3: 'srb',
                id: 688,
                name: 'Serbia',
              },
              {
                alpha2: 'sc',
                alpha3: 'syc',
                id: 690,
                name: 'Seychelles',
              },
              {
                alpha2: 'sl',
                alpha3: 'sle',
                id: 694,
                name: 'Sierra Leone',
              },
              {
                alpha2: 'sg',
                alpha3: 'sgp',
                id: 702,
                name: 'Singapore',
              },
              {
                alpha2: 'sk',
                alpha3: 'svk',
                id: 703,
                name: 'Slovakia',
              },
              {
                alpha2: 'si',
                alpha3: 'svn',
                id: 705,
                name: 'Slovenia',
              },
              {
                alpha2: 'sb',
                alpha3: 'slb',
                id: 90,
                name: 'Solomon Islands',
              },
              {
                alpha2: 'so',
                alpha3: 'som',
                id: 706,
                name: 'Somalia',
              },
              {
                alpha2: 'za',
                alpha3: 'zaf',
                id: 710,
                name: 'South Africa',
              },
              {
                alpha2: 'ss',
                alpha3: 'ssd',
                id: 728,
                name: 'South Sudan',
              },
              {
                alpha2: 'es',
                alpha3: 'esp',
                id: 724,
                name: 'Spain',
              },
              {
                alpha2: 'lk',
                alpha3: 'lka',
                id: 144,
                name: 'Sri Lanka',
              },
              {
                alpha2: 'sd',
                alpha3: 'sdn',
                id: 729,
                name: 'Sudan',
              },
              {
                alpha2: 'sr',
                alpha3: 'sur',
                id: 740,
                name: 'Suriname',
              },
              {
                alpha2: 'se',
                alpha3: 'swe',
                id: 752,
                name: 'Sweden',
              },
              {
                alpha2: 'ch',
                alpha3: 'che',
                id: 756,
                name: 'Switzerland',
              },
              {
                alpha2: 'sy',
                alpha3: 'syr',
                id: 760,
                name: 'Syrian Arab Republic',
              },
              {
                alpha2: 'tj',
                alpha3: 'tjk',
                id: 762,
                name: 'Tajikistan',
              },
              {
                alpha2: 'tz',
                alpha3: 'tza',
                id: 834,
                name: 'Tanzania, United Republic of',
              },
              {
                alpha2: 'th',
                alpha3: 'tha',
                id: 764,
                name: 'Thailand',
              },
              {
                alpha2: 'tl',
                alpha3: 'tls',
                id: 626,
                name: 'Timor-Leste',
              },
              {
                alpha2: 'tg',
                alpha3: 'tgo',
                id: 768,
                name: 'Togo',
              },
              {
                alpha2: 'to',
                alpha3: 'ton',
                id: 776,
                name: 'Tonga',
              },
              {
                alpha2: 'tt',
                alpha3: 'tto',
                id: 780,
                name: 'Trinidad and Tobago',
              },
              {
                alpha2: 'tn',
                alpha3: 'tun',
                id: 788,
                name: 'Tunisia',
              },
              {
                alpha2: 'tr',
                alpha3: 'tur',
                id: 792,
                name: 'Türkiye',
              },
              {
                alpha2: 'tm',
                alpha3: 'tkm',
                id: 795,
                name: 'Turkmenistan',
              },
              {
                alpha2: 'tv',
                alpha3: 'tuv',
                id: 798,
                name: 'Tuvalu',
              },
              {
                alpha2: 'ug',
                alpha3: 'uga',
                id: 800,
                name: 'Uganda',
              },
              {
                alpha2: 'ua',
                alpha3: 'ukr',
                id: 804,
                name: 'Ukraine',
              },
              {
                alpha2: 'ae',
                alpha3: 'are',
                id: 784,
                name: 'United Arab Emirates',
              },
              {
                alpha2: 'gb',
                alpha3: 'gbr',
                id: 826,
                name: 'United Kingdom of Great Britain and Northern Ireland',
              },
              {
                alpha2: 'us',
                alpha3: 'usa',
                id: 840,
                name: 'United States of America',
              },
              {
                alpha2: 'uy',
                alpha3: 'ury',
                id: 858,
                name: 'Uruguay',
              },
              {
                alpha2: 'uz',
                alpha3: 'uzb',
                id: 860,
                name: 'Uzbekistan',
              },
              {
                alpha2: 'vu',
                alpha3: 'vut',
                id: 548,
                name: 'Vanuatu',
              },
              {
                alpha2: 've',
                alpha3: 'ven',
                id: 862,
                name: 'Venezuela, Bolivarian Republic of',
              },
              {
                alpha2: 'vn',
                alpha3: 'vnm',
                id: 704,
                name: 'Viet Nam',
              },
              {
                alpha2: 'ye',
                alpha3: 'yem',
                id: 887,
                name: 'Yemen',
              },
              {
                alpha2: 'zm',
                alpha3: 'zmb',
                id: 894,
                name: 'Zambia',
              },
              {
                alpha2: 'zw',
                alpha3: 'zwe',
                id: 716,
                name: 'Zimbabwe',
              },
            ],
          },
          {
            name: 'locale',
            value: setup.defaultLocale,
          },
          {
            name: 'locales',
            value: {
              'de-DE': 'Deutsch',
              'en-US': 'English (USA)',
              'es-ES': 'Español',
              'fr-FR': 'Français ',
              'gl-ES': 'Galego',
              'hu-HU': 'Magyar',
              'is-IS': 'Íslenska',
              'ja-JP': '日本語',
              'lt-LT': 'Lietuvių',
              'nb-NO': 'Norsk (bokmål)',
              'nn-NO': 'Norsk (nynorsk)',
              'pt-BR': 'Português (Brasil)',
              'ro-RO': 'Română',
            },
          },
        ],
        featureFlags: [],
        ltiPlatforms: [],
        ltiRegistrations: [
          {
            clientId: 'lti-backoffice-deliver',
            deploymentIds: [
              '1',
            ],
            id: 'lti-backoffice-deliver',
            platformId: 'backoffice-platform',
            platformJwksUrl: 'https://%s/backoffice/taoLti/Security/jwks' % setup.publicDomain,
            platformKeyChain: {},
            toolId: 'deliver-tool',
            toolJwksUrl: '%s/.well-known/jwks.json' % setup.apps['environment-management'].auth_server.http.url,
            toolKeyChain: {},
          },
        ],
        ltiRoleMappings: [],
        ltiTools: [],
        meta: {
          accountId: 'local-dev-acc',
          domainDiagnostic: 'diagnostic',
          id: '1',
          instanceId: 'nextgen-stack-local',
          label: 'nextgen-stack',
          msClientId: 'ms-fe-solar-client-id',
          portalClientId: 'portal-client-id-1',
          subdomainDiagnostic: 'diagnostic',
          subdomainManualScoring: std.split(setup.publicDomain, '.')[0],
          subdomainPortal: std.split(setup.publicDomain, '.')[0],
          tenantId: '1',
        },
        metadataSchemas: [],
        oauth2Clients: [
          {
            clientId: 'dynamic-query-api-client-id',
            clientSecret: setup.lib.hash('dynamic-query-api-client-id'),
            isConfidential: true,
            name: 'Dynamic Query api OAuth2 Credentials',
            scopes: [
              'dynamic-query-api:read',
              'dynamic-query-api:write',
              'results:post',
              'api-access',
              'summary-access',
            ],
          },
          {
            clientId: 'lti-backoffice-deliver',
            clientSecret: setup.lib.hash('lti-backoffice-deliver'),
            isConfidential: false,
            name: 'Publication OAuth2 Credential',
            scopes: [
              'dynamic-query-api:read',
              'results:post',
            ],
          },
          {
            name: 'Proctoring Deliver OAuth2 Credentials',
            clientId: 'lti-deliver-proctoring',
            clientSecret: setup.lib.hash('lti-deliver-proctoring'),
            isConfidential: true,
            scopes: [
              'https://purl.imsglobal.org/spec/lti-ap/scope/control.all',
            ],
          },
          {
            clientId: 'deliver-be-devkit',
            clientSecret: setup.lib.hash('deliver-be-devkit'),
            isConfidential: true,
            name: 'Proctoring OAuth2 Credentials',
            scopes: [
              'https://purl.imsglobal.org/spec/lti-ap/scope/control.all',
            ],
          },
          {
            clientId: 'ss-solar-client-id-for-response-handlers',
            clientSecret: setup.lib.hash('ss-solar-client-id-for-response-handlers'),
            isConfidential: true,
            name: 'Scoring Service OAuth2 Client to manage response handlers',
            scopes: [
              'response-handlers:manage',
            ],
            users: [],
          },
          {
            clientId: 'ss-solar-client-id-for-tao',
            clientSecret: setup.lib.hash('ss-solar-client-id-for-tao'),
            isConfidential: true,
            name: 'Scoring Service OAuth2 Client for TAO to post events',
            scopes: [
              'event:post',
            ],
            users: [],
          },
          {
            clientId: 'ss-solar-client-id-for-ms',
            clientSecret: setup.lib.hash('ss-solar-client-id-for-ms'),
            isConfidential: true,
            name: 'Scoring Service OAuth2 Client for Manual Scoring to post scores',
            scopes: [
              'scores:post',
            ],
            users: [],
          },
          {
            clientId: 'ss-solar-client-id-for-ms-lti',
            clientSecret: setup.lib.hash('ss-solar-client-id-for-ms-lti'),
            isConfidential: true,
            name: 'Scoring Service OAuth2 Client for Manual Scoring LTI Launch',
            scopes: [],
            users: [],
          },
          {
            clientId: 'ms-client-id-for-ss',
            clientSecret: setup.lib.hash('ms-client-id-for-ss'),
            isConfidential: true,
            name: 'MS OAuth2 Client for Scoring Service to send responses and deliveries',
            scopes: [
              'delivery:post',
              'response:post',
            ],
            users: [],
          },
          {
            clientId: 'ms-fe-solar-client-id',
            isConfidential: false,
            name: 'Manual Scoring Frontend OAuth2 Client',
            scopes: [],
            usersSource: 'SCORING',
          },
          {
            clientId: 'deliver-client-id-for-ss',
            clientSecret: setup.lib.hash('deliver-client-id-for-ss'),
            isConfidential: true,
            name: 'Deliver OAuth2 Client for Scoring Service to download results',
            scopes: [],
            users: [],
          },
          {
            clientId: 'portal-client-id-1',
            isConfidential: false,
            name: 'Portal Frontend OAuth2 Client',
            scopes: [],
            usersSource: 'PORTAL',
          },
          {
            clientId: 'tenant-api-client-id',
            clientSecret: setup.lib.hash('tenant-api-client-id'),
            isConfidential: true,
            name: 'Tenant API Client',
            scopes: [
              'tenant-api:full-access',
            ],
            users: [],
          },
        ],
      },
    ],
  }
