version: '3'

method: checksum
output: prefixed
interval: 1s

env:
  NODE_VERSION: '24'
  BUILD_NPM_REGISTRY: 'http://npm-registry:4873/'
  BUILD_COMPOSER_REGISTRY: 'http://composer-registry:4060/'

tasks:
  read-aloud-client-fe:
    dir: "{{.ROOT_DIR}}/packages/read-aloud-client-fe"
    cmd: |
        /bin/bash <<"EORUN"
          . {{.ROOT_DIR}}/hack/utils/dev.inc.sh
          dev_npm_registry $BUILD_NPM_REGISTRY
          npm install --no-package-lock
          npm run build
          npm publish --registry=$BUILD_NPM_REGISTRY
        EORUN
  live-design-system:
    dir: "{{.ROOT_DIR}}/packages/live-design-system"
    cmd: |
        /bin/bash <<"EORUN"
          . {{.ROOT_DIR}}/hack/utils/dev.inc.sh
          dev_npm_registry $BUILD_NPM_REGISTRY
          npm install --no-package-lock
          npx lerna bootstrap --force-local
          npx lerna exec -- 'npm unpublish -f --registry=$BUILD_NPM_REGISTRY || true'
          npx lerna exec -- 'npm publish --registry=$BUILD_NPM_REGISTRY'
        EORUN

  tao-deliver-fe:
    dir: "{{.ROOT_DIR}}/apps/deliver/src/fe"
    cmd: |
        /bin/bash <<"EORUN"
          . {{.ROOT_DIR}}/hack/utils/dev.inc.sh
          dev_npm_registry $BUILD_NPM_REGISTRY
          ls packages/*/package.json | while read package; do
            u=$(mktemp)
            jq 'del(.private)' $package >$u
            mv $u $package
          done
          u=$(mktemp)
          jq '.files = ["dist", "server.js"]' packages/deliver-app/package.json >$u
          mv $u packages/deliver-app/package.json
          npm install --no-package-lock
          npx lerna bootstrap --force-local
          npm run build:app
          npx lerna exec -- 'npm unpublish -f --registry=$BUILD_NPM_REGISTRY || true'
          npx lerna exec -- 'npm publish --registry=$BUILD_NPM_REGISTRY'
        EORUN

  extension-tao-test-preview-ui-loader:
    dir: "{{.ROOT_DIR}}/packages/extension-tao-test-preview-ui-loader"
    cmd: |
        /bin/bash <<"EORUN"
          . {{.ROOT_DIR}}/hack/utils/dev.inc.sh
          cd views
          dev_npm_registry $BUILD_NPM_REGISTRY
          npm install -fS --package-lock-only \
            @oat-sa-private/ui-identity@latest \
            @oat-sa-private/tao-test-runner-qtinui@latest
        EORUN

  satis:
    dir: "{{.ROOT_DIR}}/build/satis"
    cmd: |
        /bin/bash <<"EORUN"
          . {{.ROOT_DIR}}/hack/utils/dev.inc.sh
          mkdir -p {{.ROOT_DIR}}/.cache/build/satis
          podman run \
            -w /app \
            -e SATIS_HOMEPAGE=$BUILD_COMPOSER_REGISTRY \
            -v {{.ROOT_DIR}}/build/satis:/config:ro \
            -v {{.ROOT_DIR}}/apps/environment-management/src/libs:/app/apps/environment-management/libs \
            -v {{.ROOT_DIR}}/packages:/app/packages \
            -v {{.ROOT_DIR}}/.cache/build/satis:/output \
            --rm docker.io/composer/satis build -vvvn /config/satis.json /output
        EORUN
