# syntax=docker/dockerfile:1-labs

ARG BUILD_IMAGE
ARG BUILD_NPM_REGISTRY

 ## ms-fe-bootstrap #####################################################################
FROM $BUILD_IMAGE AS ms-fe
ARG BUILD_IMAGE
ARG BUILD_NPM_REGISTRY

ENV NODE_VERSION="24"
ENV NODE_ENV=dev
WORKDIR /app

COPY --from=src-ms-fe . .

#define NPM_INSTALL_PACKAGES @oat-sa-private/ui-components@latest @oat-sa-private/ui-core@latest @oat-sa-private/ui-elements@latest @oat-sa-private/ui-identity@latest
#include <npm/install.in>
#define NPM_DEV
#include <npm/ci.in>
#define NPM_RUN_ARGS generate:locale build:bootstrap build:static
#include <npm/run.in>
#include <clean-app.in>

 ## ms-be ####################################################################
FROM $BUILD_IMAGE AS ms-be
ARG BUILD_IMAGE
ARG BUILD_COMPOSER_REGISTRY
ARG STATE_ROOT="/var/lib/tao-ce/scoring/ms-be"
ENV STATE_ROOT=$STATE_ROOT

WORKDIR /app
COPY --from=src-ms ./composer.json ./symfony.lock ./

#include <composer/patch.in>
#include <symfony/patch.in>
RUN jq '. \
    | .require["oat-sa/lib-grader-messenger-bridge"] = "dev-main as 5.4.0" \
    | .require["doctrine/doctrine-fixtures-bundle"] = "^3.4" \
    | .require["symfony/debug-bundle"] = "~6.4.0" \
' <composer.json >composer.json.tmp && mv composer.json.tmp composer.json

COPY --from=src-ms --exclude=**/composer.lock --exclude=**/composer.json --exclude=**/symfony.lock . .

#define COMPOSER_INSTALL_OPTS -a --no-scripts
#include <composer/install.in>
#include <clean-app.in>
RUN STATE_DATA(data,var)

 ## ss-be ####################################################################
FROM $BUILD_IMAGE AS ss-be
ARG BUILD_IMAGE
ARG STATE_ROOT="/var/lib/tao-ce/scoring/ss"
ARG BUILD_COMPOSER_REGISTRY
ENV STATE_ROOT=$STATE_ROOT

WORKDIR /app
COPY --from=src-ss ./composer.json ./symfony.lock ./
#include <composer/patch.in>
#include <symfony/patch.in>
RUN jq '. \
    | .require["oat-sa/lib-grader-messenger-bridge"] = "dev-main as 5.4.0" \
    | .require["doctrine/doctrine-fixtures-bundle"] = "^3.4" \
' <composer.json >composer.json.tmp && mv composer.json.tmp composer.json

COPY --from=src-ss --exclude=**/composer.lock --exclude=**/composer.json --exclude=**/symfony.lock . .

#define COMPOSER_INSTALL_OPTS -a --no-scripts
#include <composer/install.in>
#include <clean-app.in>
RUN STATE_DATA(data,var)

 ## Export #####################################################################
FROM scratch AS export

COPY --link --from=ms-be \
    /app /ms-be
COPY --link --from=ss-be \
    /app /ss
COPY --link --from=ms-fe \
    /app/server.cjs /ms-fe/bootstrap/
COPY --link --from=ms-fe \
    /app/dist /ms-fe/static

## COPY route files
COPY ./router.php /ms-be/router.php
COPY ./router.php /ms-be/public/router.php
COPY ./router.php /ss/router.php
COPY ./router.php /ss/public/router.php


COPY meta /meta
