on: # rebuild any PRs and main branch changes
  push:

env:
  APPS: |
    {
      "hierarchy": {
        "context": "./apps/hierarchy",
        "build-contexts": {
          "src-backend": "./src"
        }
      } 
    }

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-env:
    strategy:
      fail-fast: true
      matrix:
        image: [build-base, build-go]
    uses: ./.github/workflows/build-image.yml
    with:
      image: "${{ matrix.image }}"
      target: "${{ matrix.image }}"

  build-apps:
    needs: [build-env]
    strategy:
      fail-fast: true
      matrix:
        app: [hierarchy]
    uses: ./.github/workflows/build-image.yml
    with:
      image: "${{ matrix.app }}"
      submodules: 'recursive'
      namespace: "apps"
      context: "${{ fromJSON(env.APPS)[matrix.app].context }}"
      build-contexts: "${{ fromJSON(env.APPS)[matrix.app].build-contexts }}"
