on: # rebuild any PRs and main branch changes
  push:



permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-env:
    strategy:
      fail-fast: true
      matrix:
        image: [build-base, build-go]
    uses: ./.github/workflows/build-image.yml
    with:
      image: "${{ matrix.image }}"
      target: "${{ matrix.image }}"

  build-apps:
    needs: [build-env]
    strategy:
      fail-fast: true
      matrix:
        include:
        - app: hierarchy
          context: ./apps/hierarchy
          build-contexts: |
            src-backend=./src
          build-args: |
            BUILD_IMAGE=ghcr.io/tao-ce/tao-ce/build-base:sha-9dcb8b7
    uses: ./.github/workflows/build-image.yml
    with:
      image: "${{ matrix.app }}"
      submodules: 'recursive'
      namespace: "apps"
      context: "${{ matrix.context }}"
      build-contexts: "${{ matrix.build-contexts }}"
      build-args: "${{ matrix.build-args }}"
